---
- name: Install filebeat
  hosts: all
  roles:
    - installAnybeat
      vars:
        targetElasticsearchServer: "192.168.1.113"
        targetElasticsearchPort: "9200"
        theBeat: "filebeat"

