---
- name: Install filebeat
  hosts: all

  tasks:
  - name: Setup keys and repos for filebeat (RH)
    block:

    - name: Import filebeat key
      rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Create yum file for filebeat
      yum_repository:
        file: elasticsearch
        name: "elasticsearch-7.x"
        description: Elasticsearch repository for 7.x packages
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgcheck: 1
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: 1
        
    - name: install the latest version of filebeat
      dnf:
        name: filebeat
        state: latest

    when: ansible_facts['os_family'] == "RedHat"

  - name: Setup keys and repos for filebeat (Debian)
    block:

    - name: Import elastic key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
        
     - name: Import repo
       apt_repository:
         repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
         state: present
         
    - name: Install filebeat
      apt:
        name: filebeat
        state: present
        
    when: ansible_facts['os_family'] == "Debian"

  - name: enable system module in filebeat
    shell: filebeat modules enable system

  - name: Remove localhost target for elastic
    lineinfile:
      path: /etc/filebeat/filebeat.yml
      state: absent
      regexp: '^  hosts: \[\"localhost:9200\"\]'

  - name: point filebeat at our server
    blockinfile:
      path: /etc/filebeat/filebeat.yml
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      insertafter: "output.elasticsearch:"
      block: |2
          hosts: ["{{ targetElasticsearchServer }}:{{ targetElasticsearchPort }}"]

  - name: enable service filebeat
    systemd:
      name: filebeat
      enabled: yes
      state: started
      
    when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version']|int >= 6) or
           ansible_facts['os_family'] == "Debian"

